# Generated by Django 5.1.3 on 2024-11-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_inquiry_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
